openapi: 3.0.1
info:
  title: Pulp 3 API
  version: v3
servers:
- url: http://localhost:24817/
security:
- Basic: []
tags:
- name: content
  x-displayName: Content
- name: distributions
  x-displayName: Distributions
- name: remotes
  x-displayName: Remotes
- name: pulp_ansible
  x-displayName: Pulp_Ansible
paths:
  /pulp/api/v3/content/ansible/collections/:
    get:
      description: ViewSet for Ansible Collection.
      operationId: content_ansible_collections_list
      parameters:
      - description: Filter results where name matches value
        in: query
        name: name
        schema:
          type: string
      - description: Filter results where namespace matches value
        in: query
        name: namespace
        schema:
          type: string
      - description: Filter results where version matches value
        in: query
        name: version
        schema:
          type: string
      - description: Repository Version referenced by HREF
        in: query
        name: repository_version
        schema:
          type: string
      - description: Repository Version referenced by HREF
        in: query
        name: repository_version_added
        schema:
          type: string
      - description: Repository Version referenced by HREF
        in: query
        name: repository_version_removed
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: ""
      summary: List collections
      tags:
      - content
    post:
      description: ViewSet for Ansible Collection.
      operationId: content_ansible_collections_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collection'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
          description: ""
      summary: Create a collection
      tags:
      - content
      x-codegen-request-body-name: data
  '{collection_href}':
    get:
      description: Get the detail view of a Collection.
      operationId: pulp_ansible_galaxy_api_v2_collections_read
      parameters:
      - description: 'URI of Collection. e.g.: /pulp_ansible/galaxy/1/api/v2/collections/1/1/'
        in: path
        name: collection_href
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GalaxyCollection'
          description: ""
      tags:
      - pulp_ansible
  /pulp/api/v3/content/ansible/roles/:
    get:
      description: ViewSet for Role.
      operationId: content_ansible_roles_list
      parameters:
      - description: Filter results where name matches value
        in: query
        name: name
        schema:
          type: string
      - description: Filter results where namespace matches value
        in: query
        name: namespace
        schema:
          type: string
      - description: Filter results where version matches value
        in: query
        name: version
        schema:
          type: string
      - description: Repository Version referenced by HREF
        in: query
        name: repository_version
        schema:
          type: string
      - description: Repository Version referenced by HREF
        in: query
        name: repository_version_added
        schema:
          type: string
      - description: Repository Version referenced by HREF
        in: query
        name: repository_version_removed
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: ""
      summary: List roles
      tags:
      - content
    post:
      description: ViewSet for Role.
      operationId: content_ansible_roles_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
          description: ""
      summary: Create a role
      tags:
      - content
      x-codegen-request-body-name: data
  '{role_href}':
    get:
      description: ViewSet for Role.
      operationId: content_ansible_roles_read
      parameters:
      - description: 'URI of Role. e.g.: /pulp/api/v3/content/ansible/roles/1/'
        in: path
        name: role_href
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
          description: ""
      summary: Inspect a role
      tags:
      - content
  /pulp/api/v3/distributions/ansible/ansible/:
    get:
      description: ViewSet for Ansible Distributions.
      operationId: distributions_ansible_ansible_list
      parameters:
      - in: query
        name: name
        schema:
          type: string
      - description: Filter results where name is in a comma-separated list of values
        in: query
        name: name__in
        schema:
          type: string
      - in: query
        name: base_path
        schema:
          type: string
      - description: Filter results where base_path contains value
        in: query
        name: base_path__contains
        schema:
          type: string
      - description: Filter results where base_path contains value
        in: query
        name: base_path__icontains
        schema:
          type: string
      - description: Filter results where base_path is in a comma-separated list of
          values
        in: query
        name: base_path__in
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: ""
      summary: List ansible distributions
      tags:
      - distributions
    post:
      description: Trigger an asynchronous create task
      operationId: distributions_ansible_ansible_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnsibleDistribution'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Create an ansible distribution
      tags:
      - distributions
      x-codegen-request-body-name: data
  '{ansible_distribution_href}':
    delete:
      description: Trigger an asynchronous delete task
      operationId: distributions_ansible_ansible_delete
      parameters:
      - description: 'URI of Ansible Distribution. e.g.: /pulp/api/v3/distributions/ansible/ansible/1/'
        in: path
        name: ansible_distribution_href
        required: true
        schema:
          type: string
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Delete an ansible distribution
      tags:
      - distributions
    get:
      description: ViewSet for Ansible Distributions.
      operationId: distributions_ansible_ansible_read
      parameters:
      - description: 'URI of Ansible Distribution. e.g.: /pulp/api/v3/distributions/ansible/ansible/1/'
        in: path
        name: ansible_distribution_href
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnsibleDistribution'
          description: ""
      summary: Inspect an ansible distribution
      tags:
      - distributions
    patch:
      description: Trigger an asynchronous partial update task
      operationId: distributions_ansible_ansible_partial_update
      parameters:
      - description: 'URI of Ansible Distribution. e.g.: /pulp/api/v3/distributions/ansible/ansible/1/'
        in: path
        name: ansible_distribution_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnsibleDistribution'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Partially update an ansible distribution
      tags:
      - distributions
      x-codegen-request-body-name: data
    put:
      description: Trigger an asynchronous update task
      operationId: distributions_ansible_ansible_update
      parameters:
      - description: 'URI of Ansible Distribution. e.g.: /pulp/api/v3/distributions/ansible/ansible/1/'
        in: path
        name: ansible_distribution_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnsibleDistribution'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Update an ansible distribution
      tags:
      - distributions
      x-codegen-request-body-name: data
  /pulp/api/v3/remotes/ansible/ansible/:
    get:
      description: ViewSet for Ansible Remotes.
      operationId: remotes_ansible_ansible_list
      parameters:
      - in: query
        name: name
        schema:
          type: string
      - description: Filter results where name is in a comma-separated list of values
        in: query
        name: name__in
        schema:
          type: string
      - description: Filter results where _last_updated is less than value
        in: query
        name: _last_updated__lt
        schema:
          type: string
      - description: Filter results where _last_updated is less than or equal to value
        in: query
        name: _last_updated__lte
        schema:
          type: string
      - description: Filter results where _last_updated is greater than value
        in: query
        name: _last_updated__gt
        schema:
          type: string
      - description: Filter results where _last_updated is greater than or equal to
          value
        in: query
        name: _last_updated__gte
        schema:
          type: string
      - description: Filter results where _last_updated is between two comma separated
          values
        in: query
        name: _last_updated__range
        schema:
          type: string
      - description: ISO 8601 formatted dates are supported
        in: query
        name: _last_updated
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
          description: ""
      summary: List ansible remotes
      tags:
      - remotes
    post:
      description: ViewSet for Ansible Remotes.
      operationId: remotes_ansible_ansible_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnsibleRemote'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnsibleRemote'
          description: ""
      summary: Create an ansible remote
      tags:
      - remotes
      x-codegen-request-body-name: data
  '{ansible_remote_href}':
    delete:
      description: Trigger an asynchronous delete task
      operationId: remotes_ansible_ansible_delete
      parameters:
      - description: 'URI of Ansible Remote. e.g.: /pulp/api/v3/remotes/ansible/ansible/1/'
        in: path
        name: ansible_remote_href
        required: true
        schema:
          type: string
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Delete an ansible remote
      tags:
      - remotes
    get:
      description: ViewSet for Ansible Remotes.
      operationId: remotes_ansible_ansible_read
      parameters:
      - description: 'URI of Ansible Remote. e.g.: /pulp/api/v3/remotes/ansible/ansible/1/'
        in: path
        name: ansible_remote_href
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnsibleRemote'
          description: ""
      summary: Inspect an ansible remote
      tags:
      - remotes
    patch:
      description: Trigger an asynchronous partial update task
      operationId: remotes_ansible_ansible_partial_update
      parameters:
      - description: 'URI of Ansible Remote. e.g.: /pulp/api/v3/remotes/ansible/ansible/1/'
        in: path
        name: ansible_remote_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnsibleRemote'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Partially update an ansible remote
      tags:
      - remotes
      x-codegen-request-body-name: data
    put:
      description: Trigger an asynchronous update task
      operationId: remotes_ansible_ansible_update
      parameters:
      - description: 'URI of Ansible Remote. e.g.: /pulp/api/v3/remotes/ansible/ansible/1/'
        in: path
        name: ansible_remote_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnsibleRemote'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Update an ansible remote
      tags:
      - remotes
      x-codegen-request-body-name: data
  '{ansible_remote_href}sync/':
    post:
      description: Trigger an asynchronous task to sync Ansible content.
      operationId: remotes_ansible_ansible_sync
      parameters:
      - description: 'URI of Ansible Remote. e.g.: /pulp/api/v3/remotes/ansible/ansible/1/'
        in: path
        name: ansible_remote_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositorySyncURL'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      tags:
      - remotes
      x-codegen-request-body-name: data
  /pulp/api/v3/remotes/ansible/collection/:
    get:
      description: ViewSet for Collection Remotes.
      operationId: remotes_ansible_collection_list
      parameters:
      - in: query
        name: name
        schema:
          type: string
      - description: Filter results where name is in a comma-separated list of values
        in: query
        name: name__in
        schema:
          type: string
      - description: Filter results where _last_updated is less than value
        in: query
        name: _last_updated__lt
        schema:
          type: string
      - description: Filter results where _last_updated is less than or equal to value
        in: query
        name: _last_updated__lte
        schema:
          type: string
      - description: Filter results where _last_updated is greater than value
        in: query
        name: _last_updated__gt
        schema:
          type: string
      - description: Filter results where _last_updated is greater than or equal to
          value
        in: query
        name: _last_updated__gte
        schema:
          type: string
      - description: Filter results where _last_updated is between two comma separated
          values
        in: query
        name: _last_updated__range
        schema:
          type: string
      - description: ISO 8601 formatted dates are supported
        in: query
        name: _last_updated
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
          description: ""
      summary: List collection remotes
      tags:
      - remotes
    post:
      description: ViewSet for Collection Remotes.
      operationId: remotes_ansible_collection_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectionRemote'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionRemote'
          description: ""
      summary: Create a collection remote
      tags:
      - remotes
      x-codegen-request-body-name: data
  '{collection_remote_href}':
    delete:
      description: Trigger an asynchronous delete task
      operationId: remotes_ansible_collection_delete
      parameters:
      - description: 'URI of Collection Remote. e.g.: /pulp/api/v3/remotes/ansible/collection/1/'
        in: path
        name: collection_remote_href
        required: true
        schema:
          type: string
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Delete a collection remote
      tags:
      - remotes
    get:
      description: ViewSet for Collection Remotes.
      operationId: remotes_ansible_collection_read
      parameters:
      - description: 'URI of Collection Remote. e.g.: /pulp/api/v3/remotes/ansible/collection/1/'
        in: path
        name: collection_remote_href
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionRemote'
          description: ""
      summary: Inspect a collection remote
      tags:
      - remotes
    patch:
      description: Trigger an asynchronous partial update task
      operationId: remotes_ansible_collection_partial_update
      parameters:
      - description: 'URI of Collection Remote. e.g.: /pulp/api/v3/remotes/ansible/collection/1/'
        in: path
        name: collection_remote_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectionRemote'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Partially update a collection remote
      tags:
      - remotes
      x-codegen-request-body-name: data
    put:
      description: Trigger an asynchronous update task
      operationId: remotes_ansible_collection_update
      parameters:
      - description: 'URI of Collection Remote. e.g.: /pulp/api/v3/remotes/ansible/collection/1/'
        in: path
        name: collection_remote_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectionRemote'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      summary: Update a collection remote
      tags:
      - remotes
      x-codegen-request-body-name: data
  '{collection_remote_href}sync/':
    post:
      description: Trigger an asynchronous task to sync Collection content.
      operationId: remotes_ansible_collection_sync
      parameters:
      - description: 'URI of Collection Remote. e.g.: /pulp/api/v3/remotes/ansible/collection/1/'
        in: path
        name: collection_remote_href
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositorySyncURL'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ""
      tags:
      - remotes
      x-codegen-request-body-name: data
  /pulp_ansible/galaxy/{path}/api/:
    get:
      description: Return a response to the "GET" action.
      operationId: pulp_ansible_galaxy_api_list
      parameters:
      - in: path
        name: path
        required: true
        schema:
          type: string
      responses:
        200:
          content: {}
          description: ""
      tags:
      - pulp_ansible
  /pulp_ansible/galaxy/{path}/api/v1/roles/:
    get:
      description: APIView for Roles.
      operationId: pulp_ansible_galaxy_api_v1_roles_list
      parameters:
      - in: path
        name: path
        required: true
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
          description: ""
      tags:
      - pulp_ansible
  /pulp_ansible/galaxy/{path}/api/v1/roles/{role_pk}/versions/:
    get:
      description: APIView for Role Versions.
      operationId: pulp_ansible_galaxy_api_v1_roles_versions_list
      parameters:
      - in: path
        name: path
        required: true
        schema:
          type: string
      - in: path
        name: role_pk
        required: true
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
          description: ""
      tags:
      - pulp_ansible
  /pulp_ansible/galaxy/{path}/api/v2/collections/:
    post:
      description: Queues a task that creates a new Collection from an uploaded artifact.
      operationId: pulp_ansible_galaxy_api_v2_collections_create
      parameters:
      - in: path
        name: path
        required: true
        schema:
          type: string
      responses:
        201:
          content: {}
          description: ""
      tags:
      - pulp_ansible
  '{collection_href}versions/':
    get:
      description: APIView for Collections by namespace/name.
      operationId: pulp_ansible_galaxy_api_v2_collections_versions_list
      parameters:
      - description: 'URI of Collection. e.g.: /pulp_ansible/galaxy/1/api/v2/collections/1/1/'
        in: path
        name: collection_href
        required: true
        schema:
          type: string
      - description: A page number within the paginated result set.
        in: query
        name: page
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
          description: ""
      tags:
      - pulp_ansible
components:
  schemas:
    Collection:
      example:
        _href: https://openapi-generator.tech
        _artifact: https://openapi-generator.tech
        _created: 2000-01-23T04:56:07.000+00:00
        _type: _type
        name: name
        namespace: namespace
        version: version
      properties:
        _artifact:
          description: Artifact file representing the physical content
          format: uri
          title: ' artifact'
          type: string
        _href:
          format: uri
          readOnly: true
          title: ' href'
          type: string
        _type:
          minLength: 1
          readOnly: true
          title: ' type'
          type: string
        _created:
          description: Timestamp of creation.
          format: date-time
          readOnly: true
          title: ' created'
          type: string
        version:
          minLength: 1
          title: Version
          type: string
        name:
          minLength: 1
          title: Name
          type: string
        namespace:
          minLength: 1
          title: Namespace
          type: string
      required:
      - _artifact
      - name
      - namespace
      - version
      type: object
    Role:
      example:
        _href: https://openapi-generator.tech
        _artifact: https://openapi-generator.tech
        _created: 2000-01-23T04:56:07.000+00:00
        _type: _type
        name: name
        namespace: namespace
        version: version
      properties:
        _artifact:
          description: Artifact file representing the physical content
          format: uri
          title: ' artifact'
          type: string
        _href:
          format: uri
          readOnly: true
          title: ' href'
          type: string
        _type:
          minLength: 1
          readOnly: true
          title: ' type'
          type: string
        _created:
          description: Timestamp of creation.
          format: date-time
          readOnly: true
          title: ' created'
          type: string
        version:
          minLength: 1
          title: Version
          type: string
        name:
          minLength: 1
          title: Name
          type: string
        namespace:
          minLength: 1
          title: Namespace
          type: string
      required:
      - _artifact
      - name
      - namespace
      - version
      type: object
    AnsibleDistribution:
      example:
        _href: https://openapi-generator.tech
        _created: 2000-01-23T04:56:07.000+00:00
        base_url: base_url
        name: name
        base_path: base_path
        repository_version: https://openapi-generator.tech
        repository: https://openapi-generator.tech
        content_guard: https://openapi-generator.tech
      properties:
        _href:
          format: uri
          readOnly: true
          title: ' href'
          type: string
        _created:
          description: Timestamp of creation.
          format: date-time
          readOnly: true
          title: ' created'
          type: string
        base_path:
          description: The base (relative) path component of the published url. Avoid
            paths that                     overlap with other distribution base paths
            (e.g. "foo" and "foo/bar")
          maxLength: 255
          minLength: 1
          title: Base path
          type: string
        base_url:
          description: The URL for accessing the publication as defined by this distribution.
          minLength: 1
          readOnly: true
          title: Base url
          type: string
        content_guard:
          description: An optional content-guard.
          format: uri
          nullable: true
          title: Content guard
          type: string
        name:
          description: A unique name. Ex, `rawhide` and `stable`.
          maxLength: 255
          minLength: 1
          title: Name
          type: string
        repository:
          description: The latest RepositoryVersion for this Repository will be served.
          format: uri
          nullable: true
          title: Repository
          type: string
        repository_version:
          description: RepositoryVersion to be served
          format: uri
          nullable: true
          title: Repository version
          type: string
      required:
      - base_path
      - name
      type: object
    AsyncOperationResponse:
      example:
        task: https://openapi-generator.tech
      properties:
        task:
          description: The href of the task.
          format: uri
          title: Task
          type: string
      required:
      - task
      type: object
    AnsibleRemote:
      example:
        _href: https://openapi-generator.tech
        _type: _type
        ssl_ca_certificate: ssl_ca_certificate
        ssl_client_certificate: ssl_client_certificate
        url: url
        download_concurrency: 1
        password: password
        ssl_client_key: ssl_client_key
        _created: 2000-01-23T04:56:07.000+00:00
        name: name
        ssl_validation: true
        proxy_url: proxy_url
        _last_updated: 2000-01-23T04:56:07.000+00:00
        validate: true
        username: username
        policy: immediate
      properties:
        _href:
          format: uri
          readOnly: true
          title: ' href'
          type: string
        _created:
          description: Timestamp of creation.
          format: date-time
          readOnly: true
          title: ' created'
          type: string
        _type:
          minLength: 1
          readOnly: true
          title: ' type'
          type: string
        name:
          description: A unique name for this remote.
          minLength: 1
          title: Name
          type: string
        url:
          description: The URL of an external content source.
          minLength: 1
          title: Url
          type: string
        validate:
          description: If True, the plugin will validate imported artifacts.
          title: Validate
          type: boolean
        ssl_ca_certificate:
          description: A PEM encoded CA certificate used to validate the server certificate
            presented by the remote server. Returns SHA256 sum on GET.
          minLength: 1
          nullable: true
          title: Ssl ca certificate
          type: string
        ssl_client_certificate:
          description: A PEM encoded client certificate used for authentication. Returns
            SHA256 sum on GET.
          minLength: 1
          nullable: true
          title: Ssl client certificate
          type: string
        ssl_client_key:
          description: A PEM encoded private key used for authentication. Returns
            SHA256 sum on GET.
          minLength: 1
          nullable: true
          title: Ssl client key
          type: string
        ssl_validation:
          description: If True, SSL peer validation must be performed.
          title: Ssl validation
          type: boolean
        proxy_url:
          description: 'The proxy URL. Format: scheme://user:password@host:port'
          minLength: 1
          nullable: true
          title: Proxy url
          type: string
        username:
          description: The username to be used for authentication when syncing.
          minLength: 1
          nullable: true
          title: Username
          type: string
        password:
          description: The password to be used for authentication when syncing.
          minLength: 1
          nullable: true
          title: Password
          type: string
        _last_updated:
          description: Timestamp of the most recent update of the remote.
          format: date-time
          readOnly: true
          title: ' last updated'
          type: string
        download_concurrency:
          description: Total number of simultaneous connections.
          minimum: 1
          title: Download concurrency
          type: integer
        policy:
          default: immediate
          description: 'The policy to use when downloading content. The possible values
            include: ''immediate'', ''on_demand'', and ''cache_only''. ''immediate''
            is the default.'
          enum:
          - immediate
          - on_demand
          - streamed
          title: Policy
          type: string
      required:
      - name
      - url
      type: object
    RepositorySyncURL:
      example:
        mirror: false
        repository: https://openapi-generator.tech
      properties:
        repository:
          description: A URI of the repository to be synchronized.
          format: uri
          title: Repository
          type: string
        mirror:
          default: false
          description: If ``True``, synchronization will remove all content that is
            not present in the remote repository. If ``False``, sync will be additive
            only.
          title: Mirror
          type: boolean
      required:
      - repository
      type: object
    CollectionRemote:
      example:
        _href: https://openapi-generator.tech
        _type: _type
        ssl_ca_certificate: ssl_ca_certificate
        whitelist: whitelist
        ssl_client_certificate: ssl_client_certificate
        url: url
        download_concurrency: 1
        password: password
        ssl_client_key: ssl_client_key
        _created: 2000-01-23T04:56:07.000+00:00
        name: name
        ssl_validation: true
        proxy_url: proxy_url
        _last_updated: 2000-01-23T04:56:07.000+00:00
        validate: true
        username: username
        policy: immediate
      properties:
        _href:
          format: uri
          readOnly: true
          title: ' href'
          type: string
        _created:
          description: Timestamp of creation.
          format: date-time
          readOnly: true
          title: ' created'
          type: string
        _type:
          minLength: 1
          readOnly: true
          title: ' type'
          type: string
        name:
          description: A unique name for this remote.
          minLength: 1
          title: Name
          type: string
        url:
          description: The URL of an external content source.
          minLength: 1
          title: Url
          type: string
        validate:
          description: If True, the plugin will validate imported artifacts.
          title: Validate
          type: boolean
        ssl_ca_certificate:
          description: A PEM encoded CA certificate used to validate the server certificate
            presented by the remote server. Returns SHA256 sum on GET.
          minLength: 1
          nullable: true
          title: Ssl ca certificate
          type: string
        ssl_client_certificate:
          description: A PEM encoded client certificate used for authentication. Returns
            SHA256 sum on GET.
          minLength: 1
          nullable: true
          title: Ssl client certificate
          type: string
        ssl_client_key:
          description: A PEM encoded private key used for authentication. Returns
            SHA256 sum on GET.
          minLength: 1
          nullable: true
          title: Ssl client key
          type: string
        ssl_validation:
          description: If True, SSL peer validation must be performed.
          title: Ssl validation
          type: boolean
        proxy_url:
          description: 'The proxy URL. Format: scheme://user:password@host:port'
          minLength: 1
          nullable: true
          title: Proxy url
          type: string
        username:
          description: The username to be used for authentication when syncing.
          minLength: 1
          nullable: true
          title: Username
          type: string
        password:
          description: The password to be used for authentication when syncing.
          minLength: 1
          nullable: true
          title: Password
          type: string
        _last_updated:
          description: Timestamp of the most recent update of the remote.
          format: date-time
          readOnly: true
          title: ' last updated'
          type: string
        download_concurrency:
          description: Total number of simultaneous connections.
          minimum: 1
          title: Download concurrency
          type: integer
        policy:
          default: immediate
          description: 'The policy to use when downloading content. The possible values
            include: ''immediate'', ''on_demand'', and ''cache_only''. ''immediate''
            is the default.'
          enum:
          - immediate
          - on_demand
          - streamed
          title: Policy
          type: string
        whitelist:
          minLength: 1
          title: Whitelist
          type: string
      required:
      - name
      - url
      - whitelist
      type: object
    GalaxyRole:
      example:
        name: name
        namespace: namespace
        id: id
      properties:
        id:
          readOnly: true
          title: Id
          type: string
        name:
          minLength: 1
          title: Name
          type: string
        namespace:
          minLength: 1
          title: Namespace
          type: string
      required:
      - name
      - namespace
      type: object
    GalaxyRoleVersion:
      example:
        name: name
        source: source
      properties:
        name:
          minLength: 1
          title: Name
          type: string
        source:
          readOnly: true
          title: Source
          type: string
      required:
      - name
      type: object
    GalaxyCollection:
      example:
        name: name
        namespace: namespace
        href: href
        version: version
        versions_url: versions_url
      properties:
        name:
          minLength: 1
          title: Name
          type: string
        namespace:
          minLength: 1
          title: Namespace
          type: string
        version:
          minLength: 1
          title: Version
          type: string
        href:
          readOnly: true
          title: Href
          type: string
        versions_url:
          readOnly: true
          title: Versions url
          type: string
      required:
      - name
      - namespace
      - version
      type: object
    inline_response_200:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - _href: https://openapi-generator.tech
          _artifact: https://openapi-generator.tech
          _created: 2000-01-23T04:56:07.000+00:00
          _type: _type
          name: name
          namespace: namespace
          version: version
        - _href: https://openapi-generator.tech
          _artifact: https://openapi-generator.tech
          _created: 2000-01-23T04:56:07.000+00:00
          _type: _type
          name: name
          namespace: namespace
          version: version
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/Collection'
          type: array
      required:
      - count
      - results
    inline_response_200_1:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - _href: https://openapi-generator.tech
          _artifact: https://openapi-generator.tech
          _created: 2000-01-23T04:56:07.000+00:00
          _type: _type
          name: name
          namespace: namespace
          version: version
        - _href: https://openapi-generator.tech
          _artifact: https://openapi-generator.tech
          _created: 2000-01-23T04:56:07.000+00:00
          _type: _type
          name: name
          namespace: namespace
          version: version
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/Role'
          type: array
      required:
      - count
      - results
    inline_response_200_2:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - _href: https://openapi-generator.tech
          _created: 2000-01-23T04:56:07.000+00:00
          base_url: base_url
          name: name
          base_path: base_path
          repository_version: https://openapi-generator.tech
          repository: https://openapi-generator.tech
          content_guard: https://openapi-generator.tech
        - _href: https://openapi-generator.tech
          _created: 2000-01-23T04:56:07.000+00:00
          base_url: base_url
          name: name
          base_path: base_path
          repository_version: https://openapi-generator.tech
          repository: https://openapi-generator.tech
          content_guard: https://openapi-generator.tech
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/AnsibleDistribution'
          type: array
      required:
      - count
      - results
    inline_response_200_3:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - _href: https://openapi-generator.tech
          _type: _type
          ssl_ca_certificate: ssl_ca_certificate
          ssl_client_certificate: ssl_client_certificate
          url: url
          download_concurrency: 1
          password: password
          ssl_client_key: ssl_client_key
          _created: 2000-01-23T04:56:07.000+00:00
          name: name
          ssl_validation: true
          proxy_url: proxy_url
          _last_updated: 2000-01-23T04:56:07.000+00:00
          validate: true
          username: username
          policy: immediate
        - _href: https://openapi-generator.tech
          _type: _type
          ssl_ca_certificate: ssl_ca_certificate
          ssl_client_certificate: ssl_client_certificate
          url: url
          download_concurrency: 1
          password: password
          ssl_client_key: ssl_client_key
          _created: 2000-01-23T04:56:07.000+00:00
          name: name
          ssl_validation: true
          proxy_url: proxy_url
          _last_updated: 2000-01-23T04:56:07.000+00:00
          validate: true
          username: username
          policy: immediate
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/AnsibleRemote'
          type: array
      required:
      - count
      - results
    inline_response_200_4:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - _href: https://openapi-generator.tech
          _type: _type
          ssl_ca_certificate: ssl_ca_certificate
          whitelist: whitelist
          ssl_client_certificate: ssl_client_certificate
          url: url
          download_concurrency: 1
          password: password
          ssl_client_key: ssl_client_key
          _created: 2000-01-23T04:56:07.000+00:00
          name: name
          ssl_validation: true
          proxy_url: proxy_url
          _last_updated: 2000-01-23T04:56:07.000+00:00
          validate: true
          username: username
          policy: immediate
        - _href: https://openapi-generator.tech
          _type: _type
          ssl_ca_certificate: ssl_ca_certificate
          whitelist: whitelist
          ssl_client_certificate: ssl_client_certificate
          url: url
          download_concurrency: 1
          password: password
          ssl_client_key: ssl_client_key
          _created: 2000-01-23T04:56:07.000+00:00
          name: name
          ssl_validation: true
          proxy_url: proxy_url
          _last_updated: 2000-01-23T04:56:07.000+00:00
          validate: true
          username: username
          policy: immediate
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/CollectionRemote'
          type: array
      required:
      - count
      - results
    inline_response_200_5:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - name: name
          namespace: namespace
          id: id
        - name: name
          namespace: namespace
          id: id
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/GalaxyRole'
          type: array
      required:
      - count
      - results
    inline_response_200_6:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - name: name
          source: source
        - name: name
          source: source
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/GalaxyRoleVersion'
          type: array
      required:
      - count
      - results
    inline_response_200_7:
      example:
        next: https://openapi-generator.tech
        previous: https://openapi-generator.tech
        count: 0
        results:
        - name: name
          namespace: namespace
          href: href
          version: version
          versions_url: versions_url
        - name: name
          namespace: namespace
          href: href
          version: version
          versions_url: versions_url
      properties:
        next:
          format: uri
          nullable: true
          type: string
        previous:
          format: uri
          nullable: true
          type: string
        count:
          type: integer
        results:
          items:
            $ref: '#/components/schemas/GalaxyCollection'
          type: array
      required:
      - count
      - results
  securitySchemes:
    Basic:
      scheme: basic
      type: http
